/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Permissions;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Answer
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-06T08:37:37.081Z")
public class Answer {
  @SerializedName("answer")
  private String answer = null;

  @SerializedName("answerClientSideEncryptionAlgorithm")
  private String answerClientSideEncryptionAlgorithm = null;

  @SerializedName("dateOriginalQuestion")
  private OffsetDateTime dateOriginalQuestion = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("originalQuestion")
  private String originalQuestion = null;

  @SerializedName("permissions")
  private Permissions permissions = null;

  @SerializedName("rating")
  private String rating = null;

  @SerializedName("respondentId")
  private String respondentId = null;

  @SerializedName("submittedQuestion")
  private String submittedQuestion = null;

  @SerializedName("trained")
  private Boolean trained = null;

  @SerializedName("uuid")
  private String uuid = null;

  public Answer answer(String answer) {
    this.answer = answer;
    return this;
  }

   /**
   * Get answer
   * @return answer
  **/
  @ApiModelProperty(value = "")
  public String getAnswer() {
    return answer;
  }

  public void setAnswer(String answer) {
    this.answer = answer;
  }

  public Answer answerClientSideEncryptionAlgorithm(String answerClientSideEncryptionAlgorithm) {
    this.answerClientSideEncryptionAlgorithm = answerClientSideEncryptionAlgorithm;
    return this;
  }

   /**
   * Get answerClientSideEncryptionAlgorithm
   * @return answerClientSideEncryptionAlgorithm
  **/
  @ApiModelProperty(value = "")
  public String getAnswerClientSideEncryptionAlgorithm() {
    return answerClientSideEncryptionAlgorithm;
  }

  public void setAnswerClientSideEncryptionAlgorithm(String answerClientSideEncryptionAlgorithm) {
    this.answerClientSideEncryptionAlgorithm = answerClientSideEncryptionAlgorithm;
  }

  public Answer dateOriginalQuestion(OffsetDateTime dateOriginalQuestion) {
    this.dateOriginalQuestion = dateOriginalQuestion;
    return this;
  }

   /**
   * Get dateOriginalQuestion
   * @return dateOriginalQuestion
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getDateOriginalQuestion() {
    return dateOriginalQuestion;
  }

  public void setDateOriginalQuestion(OffsetDateTime dateOriginalQuestion) {
    this.dateOriginalQuestion = dateOriginalQuestion;
  }

  public Answer email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public Answer originalQuestion(String originalQuestion) {
    this.originalQuestion = originalQuestion;
    return this;
  }

   /**
   * Get originalQuestion
   * @return originalQuestion
  **/
  @ApiModelProperty(value = "")
  public String getOriginalQuestion() {
    return originalQuestion;
  }

  public void setOriginalQuestion(String originalQuestion) {
    this.originalQuestion = originalQuestion;
  }

  public Answer permissions(Permissions permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @ApiModelProperty(value = "")
  public Permissions getPermissions() {
    return permissions;
  }

  public void setPermissions(Permissions permissions) {
    this.permissions = permissions;
  }

  public Answer rating(String rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @ApiModelProperty(value = "")
  public String getRating() {
    return rating;
  }

  public void setRating(String rating) {
    this.rating = rating;
  }

  public Answer respondentId(String respondentId) {
    this.respondentId = respondentId;
    return this;
  }

   /**
   * Get respondentId
   * @return respondentId
  **/
  @ApiModelProperty(value = "")
  public String getRespondentId() {
    return respondentId;
  }

  public void setRespondentId(String respondentId) {
    this.respondentId = respondentId;
  }

  public Answer submittedQuestion(String submittedQuestion) {
    this.submittedQuestion = submittedQuestion;
    return this;
  }

   /**
   * Get submittedQuestion
   * @return submittedQuestion
  **/
  @ApiModelProperty(value = "")
  public String getSubmittedQuestion() {
    return submittedQuestion;
  }

  public void setSubmittedQuestion(String submittedQuestion) {
    this.submittedQuestion = submittedQuestion;
  }

  public Answer trained(Boolean trained) {
    this.trained = trained;
    return this;
  }

   /**
   * Get trained
   * @return trained
  **/
  @ApiModelProperty(value = "")
  public Boolean isTrained() {
    return trained;
  }

  public void setTrained(Boolean trained) {
    this.trained = trained;
  }

  public Answer uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Answer answer = (Answer) o;
    return Objects.equals(this.answer, answer.answer) &&
        Objects.equals(this.answerClientSideEncryptionAlgorithm, answer.answerClientSideEncryptionAlgorithm) &&
        Objects.equals(this.dateOriginalQuestion, answer.dateOriginalQuestion) &&
        Objects.equals(this.email, answer.email) &&
        Objects.equals(this.originalQuestion, answer.originalQuestion) &&
        Objects.equals(this.permissions, answer.permissions) &&
        Objects.equals(this.rating, answer.rating) &&
        Objects.equals(this.respondentId, answer.respondentId) &&
        Objects.equals(this.submittedQuestion, answer.submittedQuestion) &&
        Objects.equals(this.trained, answer.trained) &&
        Objects.equals(this.uuid, answer.uuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(answer, answerClientSideEncryptionAlgorithm, dateOriginalQuestion, email, originalQuestion, permissions, rating, respondentId, submittedQuestion, trained, uuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Answer {\n");
    
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("    answerClientSideEncryptionAlgorithm: ").append(toIndentedString(answerClientSideEncryptionAlgorithm)).append("\n");
    sb.append("    dateOriginalQuestion: ").append(toIndentedString(dateOriginalQuestion)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    originalQuestion: ").append(toIndentedString(originalQuestion)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    respondentId: ").append(toIndentedString(respondentId)).append("\n");
    sb.append("    submittedQuestion: ").append(toIndentedString(submittedQuestion)).append("\n");
    sb.append("    trained: ").append(toIndentedString(trained)).append("\n");
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

