/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * JWTPayload
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-06T08:37:37.081Z")
public class JWTPayload {
  @SerializedName("iss")
  private String iss = null;

  @SerializedName("privateClaims")
  private Map<String, String> privateClaims = null;

  @SerializedName("sub")
  private String sub = null;

  public JWTPayload iss(String iss) {
    this.iss = iss;
    return this;
  }

   /**
   * Get iss
   * @return iss
  **/
  @ApiModelProperty(value = "")
  public String getIss() {
    return iss;
  }

  public void setIss(String iss) {
    this.iss = iss;
  }

  public JWTPayload privateClaims(Map<String, String> privateClaims) {
    this.privateClaims = privateClaims;
    return this;
  }

  public JWTPayload putPrivateClaimsItem(String key, String privateClaimsItem) {
    if (this.privateClaims == null) {
      this.privateClaims = new HashMap<String, String>();
    }
    this.privateClaims.put(key, privateClaimsItem);
    return this;
  }

   /**
   * Get privateClaims
   * @return privateClaims
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getPrivateClaims() {
    return privateClaims;
  }

  public void setPrivateClaims(Map<String, String> privateClaims) {
    this.privateClaims = privateClaims;
  }

  public JWTPayload sub(String sub) {
    this.sub = sub;
    return this;
  }

   /**
   * Get sub
   * @return sub
  **/
  @ApiModelProperty(value = "")
  public String getSub() {
    return sub;
  }

  public void setSub(String sub) {
    this.sub = sub;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JWTPayload jwTPayload = (JWTPayload) o;
    return Objects.equals(this.iss, jwTPayload.iss) &&
        Objects.equals(this.privateClaims, jwTPayload.privateClaims) &&
        Objects.equals(this.sub, jwTPayload.sub);
  }

  @Override
  public int hashCode() {
    return Objects.hash(iss, privateClaims, sub);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JWTPayload {\n");
    
    sb.append("    iss: ").append(toIndentedString(iss)).append("\n");
    sb.append("    privateClaims: ").append(toIndentedString(privateClaims)).append("\n");
    sb.append("    sub: ").append(toIndentedString(sub)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

