/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MicrosoftChannelData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-06T08:37:37.081Z")
public class MicrosoftChannelData {
  @SerializedName("teamsChannelId")
  private String teamsChannelId = null;

  @SerializedName("teamsTeamId")
  private String teamsTeamId = null;

  public MicrosoftChannelData teamsChannelId(String teamsChannelId) {
    this.teamsChannelId = teamsChannelId;
    return this;
  }

   /**
   * Get teamsChannelId
   * @return teamsChannelId
  **/
  @ApiModelProperty(value = "")
  public String getTeamsChannelId() {
    return teamsChannelId;
  }

  public void setTeamsChannelId(String teamsChannelId) {
    this.teamsChannelId = teamsChannelId;
  }

  public MicrosoftChannelData teamsTeamId(String teamsTeamId) {
    this.teamsTeamId = teamsTeamId;
    return this;
  }

   /**
   * Get teamsTeamId
   * @return teamsTeamId
  **/
  @ApiModelProperty(value = "")
  public String getTeamsTeamId() {
    return teamsTeamId;
  }

  public void setTeamsTeamId(String teamsTeamId) {
    this.teamsTeamId = teamsTeamId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MicrosoftChannelData microsoftChannelData = (MicrosoftChannelData) o;
    return Objects.equals(this.teamsChannelId, microsoftChannelData.teamsChannelId) &&
        Objects.equals(this.teamsTeamId, microsoftChannelData.teamsTeamId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(teamsChannelId, teamsTeamId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MicrosoftChannelData {\n");
    
    sb.append("    teamsChannelId: ").append(toIndentedString(teamsChannelId)).append("\n");
    sb.append("    teamsTeamId: ").append(toIndentedString(teamsTeamId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

