/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Permissions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2021-08-06T08:37:37.081Z")
public class Permissions {
  @SerializedName("groupIDs")
  private List<String> groupIDs = null;

  @SerializedName("userIDs")
  private List<String> userIDs = null;

  public Permissions groupIDs(List<String> groupIDs) {
    this.groupIDs = groupIDs;
    return this;
  }

  public Permissions addGroupIDsItem(String groupIDsItem) {
    if (this.groupIDs == null) {
      this.groupIDs = new ArrayList<String>();
    }
    this.groupIDs.add(groupIDsItem);
    return this;
  }

   /**
   * Get groupIDs
   * @return groupIDs
  **/
  @ApiModelProperty(value = "")
  public List<String> getGroupIDs() {
    return groupIDs;
  }

  public void setGroupIDs(List<String> groupIDs) {
    this.groupIDs = groupIDs;
  }

  public Permissions userIDs(List<String> userIDs) {
    this.userIDs = userIDs;
    return this;
  }

  public Permissions addUserIDsItem(String userIDsItem) {
    if (this.userIDs == null) {
      this.userIDs = new ArrayList<String>();
    }
    this.userIDs.add(userIDsItem);
    return this;
  }

   /**
   * Get userIDs
   * @return userIDs
  **/
  @ApiModelProperty(value = "")
  public List<String> getUserIDs() {
    return userIDs;
  }

  public void setUserIDs(List<String> userIDs) {
    this.userIDs = userIDs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Permissions permissions = (Permissions) o;
    return Objects.equals(this.groupIDs, permissions.groupIDs) &&
        Objects.equals(this.userIDs, permissions.userIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupIDs, userIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Permissions {\n");
    
    sb.append("    groupIDs: ").append(toIndentedString(groupIDs)).append("\n");
    sb.append("    userIDs: ").append(toIndentedString(userIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

