/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.MicrosoftBotMessage;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MicrosoftBotControllerApi
 */
@Ignore
public class MicrosoftBotControllerApiTest {

    private final MicrosoftBotControllerApi api = new MicrosoftBotControllerApi();

    
    /**
     * Handle Microsoft bot messages
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleEventsUsingPOSTTest() throws ApiException {
        MicrosoftBotMessage message = null;
        Object response = api.handleEventsUsingPOST(message);

        // TODO: test validations
    }
    
}
