/*
 * API
 * Documentation API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.SlackEventWrapper;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SlackControllerApi
 */
@Ignore
public class SlackControllerApiTest {

    private final SlackControllerApi api = new SlackControllerApi();

    
    /**
     * Handle &#39;/katie&#39; command
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void commandKatieUsingPOSTTest() throws ApiException {
        String payload = null;
        Object response = api.commandKatieUsingPOST(payload);

        // TODO: test validations
    }
    
    /**
     * Handle Slack events
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleEventsUsingPOST1Test() throws ApiException {
        SlackEventWrapper event = null;
        Object response = api.handleEventsUsingPOST1(event);

        // TODO: test validations
    }
    
    /**
     * Handle Slack interactions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void handleInteractionsUsingPOSTTest() throws ApiException {
        String payload = null;
        Object response = api.handleInteractionsUsingPOST(payload);

        // TODO: test validations
    }
    
    /**
     * OAuth2 callback for Slack
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void oauth2CallbackSlackUsingGETTest() throws ApiException {
        String code = null;
        String state = null;
        Object response = api.oauth2CallbackSlackUsingGET(code, state);

        // TODO: test validations
    }
    
}
